### ISSUE TITLE
0.2 improvements

### ISSUE THREAD

**Issue by matsjoyce** [dwjoyce/pythonbook#12]
- [x] is it possible to keep program listings on a page without page breaks in the middle?  Or put a "continued..." on the bottom right?
- [x] state operator precedence order in operators appendix.
- [x] add short description to common mistakes sections.
- [x] copyright notice
- [x] remove excess spacing in tables
- [x] consistentize chapter refs
- [x] change code hight
- [ ] I have thought of a truly marvellous improvement to this book, but this comment is too small to contain it.

**Comment by matsjoyce** [comment]
@dwjoyce Last one's yours.

**Comment by dwjoyce** [comment]
Last one done, but I expect we may get further feedback before we want to do a new release.
