### ISSUE TITLE
Remaining chapters

### ISSUE THREAD

**Issue by matsjoyce** [dwjoyce/pythonbook#5]
Just to track:
- [x] 00 - Starting with Python's IDLE
  - dwjoyce
- [x] 01 - Python as a Calculator
- [x] 02 - Naming your data
- [x] 03 - Functions and Maths
- [x] 04 - Getting help
- [x] 05 - Drawing Turtles
- [x] 06 - First program
  - dwjoyce
- [x] 07 - Print that out!
- [x] 08 - Asking questions
- [x] 09 - Performing selection
- [x] 10 - Decisions, decisions
- [x] 11 - Combining decisions together
- [x] 12 - Going loopy
- [x] 13 - Escaping the cycle
- [x] 14 - Going random
- [x] 15 - Grouping data together
- [x] 16 - Slicing sequences
- [x] 17 - Walking along data
  - dwjoyce
- [x] 18 - Naming code
  - dwjoyce
- [x] 19 - More functions
  - dwjoyce
- [x] 20 - Reading files
  - matsjoyce
- [x] 21 - Writing files
  - matsjoyce
- [x] 22 - Catching errors
  - matsjoyce

**Comment by matsjoyce** [comment]
Last two!

**Comment by dwjoyce** [comment]
Last two chapters over to you for pictures...

**Comment by matsjoyce** [comment]
All done!
